name: spielwiesn_spielothek
description: "Eine App fÃ¼r die Spielothek auf der Spielwiesn"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  csv: ^6.0.0
  http: ^1.5.0
  shared_preferences: ^2.5.3
  upgrader: ^12.1.0
  markdown_widget: ^2.3.2+8
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/Spieleliste.csv
    - assets/Imprint.md
    - assets/Privacy.md
    - assets/tri-tail_logo.png
    - assets/mpa_logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Logo.png"
  adaptive_icon_foreground: "assets/Logo_Android.png"
  adaptive_icon_background: "#ffffff"
  windows:
    generate: true
    image_path: "assets/Logo.png"
    icon_size: 256